name: "Project deployment"
on:
  push:
    inputs:
      deployment-file:
        required: true
        description: "dbx deployment file"
        default: "conf/deployment.yml"
        type: string
      run-job-now:
        required: false
        description: "if yes, runs dbr job now"
        default: "yes"
        type: string

  workflow_call:
    inputs:
      deployment-file:
        required: true
        description: "dbx deployment file"
        type: string
      run-job-now:
        required: false
        description: "if yes, runs dbr job now"
        default: "yes"
        type: string

    outputs:
      job_id:
        description: Databricks job id
        value: ${{ jobs.deploy_databricks.outputs.job_id }}
      run_id:
        description: Databricks run id
        value: ${{ jobs.deploy_databricks.outputs.run_id }}

  workflow_dispatch:
    inputs:
      deployment-file:
        required: true
        description: "dbx deployment file"
        default: "conf/deployment.yml"
        type: string
      run-job-now:
        required: false
        description: "if yes, runs dbr job now"
        default: "yes"
        type: string

jobs:
  deploy_databricks:
    outputs:
      job_id: ${{ steps.deploy_dbx.outputs.job_id }}
      run_id: ${{ steps.deploy_dbx.outputs.run_id }}
    runs-on: ubuntu-20.04
    steps:
      - name: Echo inputs
        id: echo_inputs
        run: |
          echo "Branch that was used to start the workflow: ${{ github.ref_name }}"
          echo "Github workflow started running: $(date +'%Y-%m-%d %H:%M:%S')"
          echo "Deployment file: ${{ inputs.deployment-file }}"
          echo "Run job now?: ${{ inputs.run-job-now }}"

      - name: Get composite run steps repository
        id: checkout_demo_code
        uses: actions/checkout@v3
        with:
          path: actions

      - name: Setup env vars
        id: setup_env_vars
        uses: ./actions/.github/actions/setup_env_vars
        with:
          databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
          databricks_host: ${{ secrets.DATABRICKS_HOST }}

      - name: Deploy dbx
        id: deploy_dbx
        uses: ./actions/.github/actions/deploy_dbx
        with:
          workspace-dir: ${{ format('/Shared/dbx/projects/{0}', env.PROJECT_NAME) }}
          artifact-location: ${{ format('dbfs:/dbx/{0}', env.PROJECT_NAME) }}
          deployment-file: ${{ inputs.deployment-file}}
          run-job-now: ${{ inputs.run-job-now}}